### ISSUE TITLE
x_ite has good support for externproto

### ISSUE THREAD

**Issue by andreasplesch** [michaliskambi/x3d-tests#1]
https://github.com/michaliskambi/x3d-tests/wiki/Incompatibility-in-how-relative-URLs-are-resolved%2C-when-used-together-with-EXTERNPROTO omits testing of the x_ite browser under the assumption that the browser does not support this node. In fact, x_ite has good support for protos (including externproto).

I added x_ite tests in my fork here:
https://github.com/andreasplesch/x3d-tests

https://rawgit.com/andreasplesch/x3d-tests/master/relative_urls_in_externproto/working_in_instantplayer_and_view3dscene/1/x_ite.html
https://rawgit.com/andreasplesch/x3d-tests/master/relative_urls_in_externproto/working_in_instantplayer_and_view3dscene/2/x_ite.html
https://rawgit.com/andreasplesch/x3d-tests/master/relative_urls_in_externproto/workaround_working_in_all/x_ite.html
https://rawgit.com/andreasplesch/x3d-tests/master/relative_urls_in_externproto/working_in_bscontact/1/x_ite.html
https://rawgit.com/andreasplesch/x3d-tests/master/relative_urls_in_externproto/working_in_bscontact/2/x_ite.html

It appears that x_ite behaves the same as instantplayer and view3dscene.

**Comment by michaliskambi** [comment]
Thank you -- I merged your tests into mine repository, and I will update the wiki page!
