### ISSUE TITLE
[info] some browser behaviours of externproto relative url

### ISSUE THREAD

**Issue by splace** [michaliskambi/x3d-tests#3]
for below; 

*  relative to the initially loaded files location <==> the wrong way
* relative to the file the url in in (cf html) <==> the right way

player | resolution
-|-
Cosmo | wrong way
Flux/Vivaty | right way
Cortona #6- | right way
Cortona #6 | wrong way
OpenWorlds | right way

**Comment by michaliskambi** [comment]
Thanks for testing! I added a link to this from https://github.com/michaliskambi/x3d-tests/wiki/Incompatibility-in-how-relative-URLs-are-resolved,-when-used-together-with-EXTERNPROTO .
