### ISSUE TITLE
possible root of the browser externproto relative url issues

### ISSUE THREAD

**Issue by splace** [michaliskambi/x3d-tests#4]
a long time ago i wondered if this was the source of confusion about this.....

it was common to see url's embedded in strings, often inside scripts in strings, being sent around, these could start in one file and end in some other, they were just strings so the rules about resolving url's weren't clearly applicable making it important for it to be specified.

so i wondered if its these string sourced url's that are what the spec. is actually talking about, NOT, what has been assumed by many, the directly indicated url's (where, for me, the normal url spec simply applies.) these string sourced url's are sensibly resolved, like the spec says, from where the string is stored (or possibly even generated by script).

**Comment by michaliskambi** [comment]
Good comments, thank you.

From the implementation side, I can easily see how both approaches make sense --- you need to have some base URL per-node, and neither choice is really 100% perfect for users. As I explained on https://github.com/michaliskambi/x3d-tests/wiki/Incompatibility-in-how-relative-URLs-are-resolved,-when-used-together-with-EXTERNPROTO , in some use-cases one approach is more natural, in other use-cases the other approach is natural.

Implementing the "perfect for all use-cases" scenario would be hard, as you would need to store "base URL" at every X3D field (not only at every X3D node). So noone does it.
