### ISSUE TITLE
Don't use the term gamma correction in spec or wiki

### ISSUE THREAD

**Issue by MarkCallow** [michaliskambi/x3d-tests#5]
I just came across the wiki page [Gamma-Correction-in-Future-X3D](https://github.com/michaliskambi/x3d-tests/wiki/Gamma-Correction-in-Future-X3D). Please don't refer to it as gamma correction and especially don't make statements like the 'monitor "distorts" the colors even if "distorts" is in inverted commas.

What is happening is the incoming scene data is being encoded/compressed in a way that removes all changes that humans cannot perceive thereby making the signal fit into 8-bit components without banding or losing detail in the darks. The monitor just happens to be a nearly perfect decoder for this encoding as it has the inverse response of the human eye. When you understand that this is what is going on, everything becomes much clearer.

If you have only 8-bits per channel you need this encoding. Since it is an encoding/compression you need to decode (to "linear") before performing any computations - lighting, flitering, blending etc. and re-encode afterward, if you only have an 8-bit framebuffer. If you do not re-encode, i.e. you are doing "linear" rendering then for correct color, assuming an sRGB or similar monitor, the colors in the framebuffer MUST be encoded before presentation to the display to get correct color. This is what hardware "gamma correctors" were doing on early graphics systems. This is all you need to know.

Unfortunately there are many implementations of low-level graphics apis where "linear" framebuffers are not encoded for the display - WebGL is one culprit - which has led to people tuning their colors for the incorrect rendering. Then when rendering IS done correctly they will complain that it looks terrible. WebGL does not currently support sRGB framebuffers so apps that care about correct color rendering have to encode the outputs of their fragment shaders. If blending is being used the result is not 100% correct because the encoded sRGB values rather than linear values are blended.

I recommend Poynton's [Rehabilitation of gamma](https://poynton.ca/PDFs/Rehabilitation_of_gamma.pdf) for further detail.

**Comment by michaliskambi** [comment]
That's a fair point. Talking about sRGB and linear space is more precise way to say what we want. I like how [glTF spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#materials) avoids saying things like "do gamma correction", it instead nicely says things like _"The baseColorTexture uses the sRGB transfer function and must be converted to linear space before it is used for any computations."_ .

We will indeed want to follow it for X3D spec. I.e. not say _"do gamma correction"_, but say to _"perform calculations in linear space"_, and to clarify when/which textures should be considered in sRGB. I did edits to this document to not forget about it, when we'll get back to this topic in Web3D. In particular I mention `renderingColorSpace` field (kind of similar to Unity naming, https://docs.unity3d.com/Manual/LinearRendering-LinearOrGammaWorkflow.html ) now as replacement for `gammaCorrectionDefault`.

Thanks!

Though in generally the term "gamma correction" is used widely as a synonym for "gamma-correct rendering". So my wiki will continue to talk about it. The confusing term is not my invention -- resources like

- https://www.vfxwizard.com/tutorials/gamma-correction-for-linear-workflow.html ,
- https://gamedevelopment.tutsplus.com/articles/gamma-correction-and-why-it-matters--gamedev-14466
- https://en.wikipedia.org/wiki/SRGB
- https://blog.molecular-matters.com/2011/11/21/gamma-correct-rendering/
- https://docs.unity3d.com/Manual/LinearRendering-LinearOrGammaWorkflow.html

all do talk about it. 

As for "distorts": Agreed, I have changed the term "distorts" into "transforms", and linked more clearly to https://github.com/michaliskambi/x3d-tests/wiki/Gamma-correction-in-X3D-and-glTF , that says what is this "transformation" in practice. The overview on https://github.com/michaliskambi/x3d-tests/wiki/Gamma-Correction-in-Future-X3D is deliberately at attempt at explaining the issue in a bit different way than more developer-oriented https://github.com/michaliskambi/x3d-tests/wiki/Gamma-correction-in-X3D-and-glTF .

As for 8-bits: I do not fully agree with your phrasing, although that's just going into details. But for me it's not about 8-bits or compression. It's about the need to perform calculations in the "linear" space, which is really the right space where the physical light equations make sense. And the fact that typical textures do not store colors in this space (though they could), and monitors do not take colors in this space. The important thing is not mix this with "tone mapping", https://en.wikipedia.org/wiki/Tone_mapping , which deals with "how to represent this infinite range of colors (in reality) on a limited range available on monitors". And tone mapping is independent from gamma correction -- gamma correction is just "how to calculate lighting correctly".

Agreed on sRGB framebuffers. They would be great, if universally available. If a GPU implementation can use the GPU sRGB texture formats, and sRGB framebuffer formats, then it has both an easier job, and can be more correct, as it doesn't have to effectively hardcode operations lik `pow(x, 1/2.2)` in the shader.

**Comment by MarkCallow** [comment]
Thanks for making changes.

I am well aware of the wide-spread use of "gamma correction" which has origins in the early days of CG. That is no reason to continue using it. Thinking about this issue as "correction" sets one off down the wrong path and helps lead to the widespread confusion surrounding it.

> As for 8-bits: I do not fully agree with your phrasing

Which part? Referring to sRGB as an encoding/compression is fact. Saying you need an sRGB framebuffer, if you only have 8-bits is also fact. If you store linear in there you will suffer unpleasant artifacts.

I don't agree with "`renderingColorSpace`". Rendering should always be done in linear space. It is not wise to provide people ways to do things incorrectly, so rendering in sRGB space should not be allowed. The only discussion/choice should be about whether the framebuffer is in sRGB or linear space. If the latter data should be encoded for the display before it hits the display.
